// Generated by CoffeeScript 1.4.0
var Git, GitRepo, NpmPackage, Shell,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

GitRepo = require('git-seed-core').GitRepo;

Git = require('git-seed-core').Git;

Shell = require('git-seed-core').Shell;

module.exports = NpmPackage = (function(_super) {

  __extends(NpmPackage, _super);

  function NpmPackage() {
    return NpmPackage.__super__.constructor.apply(this, arguments);
  }

  NpmPackage.manager = function() {
    return 'npm';
  };

  NpmPackage.install = function(superTask, repo, args, callback) {
    superTask.allow_stdio = true;
    return Shell.spawnAt(superTask, {
      directory: repo.workDir
    }, 'npm', ['install'], callback);
  };

  return NpmPackage;

})(GitRepo);
