// Generated by CoffeeScript 1.6.3
var Git, GitRepo, NpmPackage, Shell, join, lstatSync, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

GitRepo = require('git-seed-core').GitRepo;

Git = require('git-seed-core').Git;

Shell = require('git-seed-core').Shell;

lstatSync = require('fs').lstatSync;

join = require('path').join;

module.exports = NpmPackage = (function(_super) {
  __extends(NpmPackage, _super);

  function NpmPackage() {
    _ref = NpmPackage.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  NpmPackage.manager = function() {
    return 'npm';
  };

  NpmPackage.install = function(superTask, repo, args, callback) {
    var error, packageJSON;
    try {
      packageJSON = join(repo.workDir, 'package.json');
      lstatSync(packageJSON);
      superTask.allow_stdio = true;
      return Shell.spawnAt(superTask, {
        directory: repo.workDir
      }, 'npm', ['install'], callback);
    } catch (_error) {
      error = _error;
      superTask.notify.info('skipped', "missing " + packageJSON);
      return callback(null);
    }
  };

  return NpmPackage;

})(GitRepo);
